#!/bin/sh
rm -rf /var/lib/postgresql/*
chmod 700 /var/lib/postgresql/
chown postgres:postgres /var/lib/postgresql/
su postgres -c "/usr/lib/postgresql/9.5/bin/initdb --pgdata=/var/lib/postgresql --encoding=UTF8 --no-locale"

echo "CREATE USER bamboo;" > ./bamboo.sql
echo "CREATE USER root;" > ./bamboo.sql
echo "ALTER USER bamboo SUPERUSER;" > ./bamboo.sql
echo "ALTER USER root SUPERUSER;" > ./bamboo.sql
su postgres -c '/usr/lib/postgresql/9.5/bin/postgres --single -D /var/lib/postgresql < ./bamboo.sql'
rm ./bamboo.sql

# more opts to check
#--fsync=off --shared-buffers=2MB --temp-buffers=800kB --work-mem=64kB --maintenance-work-mem=1024kB
# --wal-buffers=32kB --checkpoint-segments=64 --seq-page-cost=0.01 --random-page-cost=0.01 --effective-cache-size=64kB

exec 2>&1
exec chpst -u postgres /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql
