#!/bin/sh
rm -rf /var/lib/postgresql/10/*
chmod 700 /var/lib/postgresql/10/
chown postgres:postgres /var/lib/postgresql/10/
su postgres -c "/usr/lib/postgresql/10/bin/initdb --pgdata=/var/lib/postgresql/10 --encoding=UTF8 --no-locale"

echo "CREATE USER bamboo;" > ./init.sql
echo "CREATE USER root;" >> ./init.sql
echo "ALTER USER bamboo SUPERUSER;" >> ./init.sql
echo "ALTER USER root SUPERUSER;" >> ./init.sql
su postgres -c '/usr/lib/postgresql/10/bin/postgres --single -D /var/lib/postgresql/10 < ./init.sql'
rm ./init.sql

# more opts to check
#--fsync=off --shared-buffers=2MB --temp-buffers=800kB --work-mem=64kB --maintenance-work-mem=1024kB
# --wal-buffers=32kB --checkpoint-segments=64 --seq-page-cost=0.01 --random-page-cost=0.01 --effective-cache-size=64kB

exec 2>&1
exec chpst -u postgres /usr/lib/postgresql/10/bin/postgres -D /var/lib/postgresql/10
