# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ github-workflows ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Registry login
        run: echo ${{ secrets.CR_PAT}} | docker login ghcr.io --username TYPO3IncTeam --password-stdin

      - name: Make BaseImage
        run: make build_baseimage
