# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ github-workflows ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changes:
              - 'baseimage/**'

      - name: Login to GitHub Container Registry
        if: steps.filter.outputs.changes == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: TYPO3IncTeam
          password: ${{ secrets.CR_PAT }}

      - name: Build Base Image
        if: steps.filter.outputs.changes == 'true'
        run: make build_baseimage

      - name: Release Base Image
        if: steps.filter.outputs.changes == 'true'
        run: make release_baseimage

  build-php-js:
    runs-on: ubuntu-latest
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        image: [ php53, php54, php55, php56, php70, php71, php72, php73, php74, bamboo, js ]

    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            matrix:
              - '${{ matrix.image }}/**'

      - name: Login to GitHub Container Registry
        if: steps.filter.outputs.matrix == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: TYPO3IncTeam
          password: ${{ secrets.CR_PAT }}

      - name: Build ${{ matrix.image }} Image
        if: steps.filter.outputs.matrix == 'true'
        run: make build_${{ matrix.image }}

      - name: Release ${{ matrix.image }} Image
        if: steps.filter.outputs.matrix == 'true'
        run: make release_${{ matrix.image }}
